# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-08 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tm500trf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tm500info',
            name='ip_list',
        ),
        migrations.AlterField(
            model_name='iperfserver',
            name='ip',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='iperfserver',
            name='port',
            field=models.IntegerField(),
        ),
    ]
