# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-08 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tm500trf', '0002_auto_20170108_0842'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TM500Info',
        ),
        migrations.AlterField(
            model_name='iperfserver',
            name='port',
            field=models.CharField(max_length=30),
        ),
    ]
