# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-08 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tm500trf', '0003_auto_20170108_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='TM500Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
            ],
        ),
    ]
