# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-09 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tm500trf', '0005_delete_tm500info'),
    ]

    operations = [
        migrations.CreateModel(
            name='TM500Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('pppoenum', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='UEInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ueip', models.CharField(max_length=20)),
                ('index', models.CharField(max_length=4)),
                ('tm500ip', models.CharField(max_length=20)),
                ('ul_trf_cmd', models.CharField(max_length=100)),
                ('dl_trf_cmd', models.CharField(max_length=100)),
                ('ul_trf_state', models.CharField(max_length=10)),
                ('dl_trf_state', models.CharField(max_length=10)),
            ],
        ),
    ]
