# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-09 06:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tm500trf', '0006_tm500info_ueinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ueinfo',
            old_name='ueip',
            new_name='ip',
        ),
    ]
