# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-09 06:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tm500trf', '0007_auto_20170109_0630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ueinfo',
            old_name='dl_trf_cmd',
            new_name='dl_cmd',
        ),
        migrations.RenameField(
            model_name='ueinfo',
            old_name='dl_trf_state',
            new_name='dl_state',
        ),
        migrations.RenameField(
            model_name='ueinfo',
            old_name='ul_trf_cmd',
            new_name='ul_cmd',
        ),
        migrations.RenameField(
            model_name='ueinfo',
            old_name='ul_trf_state',
            new_name='ul_state',
        ),
    ]
