# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-24 03:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tm500trf', '0009_auto_20170109_0637'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TM500Info',
        ),
        migrations.DeleteModel(
            name='UEInfo',
        ),
    ]
