# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-24 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tm500trf', '0010_auto_20170124_0356'),
    ]

    operations = [
        migrations.CreateModel(
            name='TM500Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('index', models.CharField(max_length=4)),
                ('pppoenum', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='UEInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20)),
                ('tm500ip', models.CharField(max_length=20)),
                ('ppp', models.CharField(max_length=20)),
                ('ul_cmd', models.CharField(max_length=100)),
                ('dl_cmd', models.CharField(max_length=100)),
                ('ul_status', models.CharField(max_length=10)),
                ('dl_status', models.CharField(max_length=10)),
            ],
        ),
    ]
