# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-24 07:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tm500trf', '0011_tm500info_ueinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UEInfo',
        ),
    ]
