# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-01 07:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tm500trf', '0014_tputinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TputInfo',
        ),
    ]
