# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-02 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tm500trf', '0020_auto_20170302_0258'),
    ]

    operations = [
        migrations.CreateModel(
            name='IperfCmd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=5)),
                ('cmd', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='IperfServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('index', models.CharField(max_length=5)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('startip', models.GenericIPAddressField()),
                ('endip', models.GenericIPAddressField()),
                ('port', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TM500',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('tma', models.GenericIPAddressField()),
                ('index', models.CharField(max_length=4)),
                ('pppoenum', models.CharField(max_length=3)),
                ('user', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20)),
                ('ppp', models.CharField(max_length=20)),
                ('ulcmd', models.CharField(max_length=100)),
                ('dlcmd', models.CharField(max_length=100)),
                ('ulstatus', models.CharField(max_length=10)),
                ('dlstatus', models.CharField(max_length=10)),
                ('tm500', models.CharField(max_length=20)),
                ('tma', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='USER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
