# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-02 07:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tm500trf', '0023_iperfcmd_iperfserver_tm500_ue_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ue',
            old_name='ppp',
            new_name='adapter',
        ),
    ]
