# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-02 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tm500trf', '0024_auto_20170302_0702'),
    ]

    operations = [
        migrations.CreateModel(
            name='PPPOE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='ue',
            name='ip',
            field=models.GenericIPAddressField(),
        ),
    ]
