# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-02 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tm500trf', '0025_auto_20170302_0859'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PPPOE',
        ),
    ]
