# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-02 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tm500trf', '0026_delete_pppoe'),
    ]

    operations = [
        migrations.CreateModel(
            name='PPPOE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tm500', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
            ],
        ),
    ]
