# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-03 07:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tm500trf', '0031_iperfcmd_iperfserver_pppoe_tm500_ue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IperfCmd',
        ),
        migrations.DeleteModel(
            name='IperfServer',
        ),
        migrations.DeleteModel(
            name='TM500',
        ),
        migrations.DeleteModel(
            name='UE',
        ),
    ]
