# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-03 08:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tm500trf', '0033_iperfcmd_iperfserver_tm500_ue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tm500',
            old_name='ppoenum',
            new_name='pppoenum',
        ),
    ]
