# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-08 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tm500trf', '0040_delete_ue'),
    ]

    operations = [
        migrations.CreateModel(
            name='UE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('index', models.CharField(max_length=20)),
                ('adapter', models.CharField(max_length=20)),
                ('ulcmd', models.CharField(max_length=100)),
                ('dlcmd', models.CharField(max_length=100)),
                ('ulstatus', models.CharField(max_length=10)),
                ('dlstatus', models.CharField(max_length=10)),
                ('tm500', models.CharField(max_length=20)),
                ('tma', models.CharField(max_length=20)),
                ('trfip', models.GenericIPAddressField()),
            ],
        ),
    ]
