# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-09 02:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tm500trf', '0041_ue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UE',
        ),
    ]
