# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-10 10:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tm500trf', '0046_auto_20170810_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iperfserver',
            old_name='ip',
            new_name='serv_ip',
        ),
    ]
