# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-11 02:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tm500trf', '0047_auto_20170810_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iperfserver',
            name='index',
        ),
    ]
