# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-12 08:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tm500trf', '0048_remove_iperfserver_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pc',
            old_name='port',
            new_name='status',
        ),
    ]
