# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-16 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tm500trf', '0049_auto_20170812_0834'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IperfServer',
        ),
        migrations.DeleteModel(
            name='PC',
        ),
    ]
