# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-04 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tm500trf', '0052_auto_20170904_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc',
            name='cqi',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='pc',
            name='dl_bler',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='pc',
            name='dl_mcs',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='pc',
            name='dl_pdcp',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='pc',
            name='earfcn',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='pc',
            name='pci',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='pc',
            name='rsrp',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='pc',
            name='sinr',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='pc',
            name='tm_mode',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='pc',
            name='ul_bler',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='pc',
            name='ul_mcs',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='pc',
            name='ul_pdcp',
            field=models.CharField(default='N/A', max_length=10),
        ),
    ]
