# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-05-09 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tm500trf', '0055_auto_20170904_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.GenericIPAddressField()),
                ('status', models.CharField(max_length=20)),
                ('owner', models.GenericIPAddressField()),
                ('kit', models.CharField(max_length=100)),
                ('note', models.CharField(max_length=100)),
                ('index', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='IperfServer',
        ),
        migrations.DeleteModel(
            name='PC',
        ),
    ]
