# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-05-10 08:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tm500trf', '0056_auto_20180509_0353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testline',
            old_name='owner',
            new_name='user',
        ),
    ]
