# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-05-12 01:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tm500trf', '0058_remove_testline_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testline',
            old_name='status',
            new_name='dlput',
        ),
        migrations.RenameField(
            model_name='testline',
            old_name='user',
            new_name='rsrp',
        ),
        migrations.RenameField(
            model_name='testline',
            old_name='kit',
            new_name='sinr',
        ),
        migrations.RemoveField(
            model_name='testline',
            name='note',
        ),
    ]
