# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-05-12 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tm500trf', '0059_auto_20180512_0112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testline',
            name='dlput',
        ),
        migrations.AddField(
            model_name='testline',
            name='dltput',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='testline',
            name='rsrp',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='testline',
            name='sinr',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
