# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-06-09 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tm500trf', '0062_testline_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='testline',
            name='tput_range',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
